Fetch all versions api v2.0 with tests
ShoppinPal/vend-nodejs-sdk pull request #28
Opened 2017-11-22 09:45 UTC by kamal0808

2017-11-22 18:20 UTC, pulkitsinghal requested changes

2017-11-22 18:20 UTC, pulkitsinghal commented on test/test.js
> +            expect(response.data).to.be.instanceof(Object);
@kamal0808 lets also check for some known common keys in the payload ... It will help alert us when the test breaks due to changes from their side.

2017-11-22 18:20 UTC, pulkitsinghal commented on vend.js
> +          'If you need to be notified of register sales, ' +
How is this better formatting than before?

2017-11-22 18:20 UTC, pulkitsinghal commented on vend.js
> +  log.silly('Authorization: ' + authString); // TODO: sensitive data ... do not log?
you might as well remove this line of code from this code block since you are adding a new feature

2017-11-22 18:20 UTC, pulkitsinghal commented on vend.js
> +  if (!dependencies.underscore) {
In the future, please be selective about which code blocks you stage and commit

2017-11-23 16:22 UTC, pulkitsinghal commented
I saw your new commit. It is fine.

From what I understand, this PR is a WIP (work in progress) so please make sure to at least do something about the testcase where I left a comment before merging this PR.

2017-11-24 22:59 UTC, kamal0808 commented
@pulkitsinghal Yeah, this was just a WIP. I had asked for your availability so that I could finish the work before that.

2018-01-09 23:29 UTC, closed without merging